#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void button_load_click( wxCommandEvent& event );
		void bitton_blur_click( wxCommandEvent& event );
		void button_erode_click( wxCommandEvent& event );
		void checko_box_check( wxCommandEvent& event );
		void panel_update( wxUpdateUIEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

};

#endif // __GUIMyFrame1__
