#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include "CImg.h"
#include <wx/generic/filedlgg.h>
#include <wx/dcbuffer.h>
#include <wx/event.h>
#include <wx/msgdlg.h>
#include "FreeImage.h"



/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void button_load_click( wxCommandEvent& event );
		void bitton_blur_click( wxCommandEvent& event );
		void buttonm_isEroded_click( wxCommandEvent& event );
		void checko_box_check( wxCommandEvent& event );
		void panel_OnPaint( wxPaintEvent& event );
		void panel_OnSize( wxSizeEvent& event );
		void panel_update( wxUpdateUIEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members


private:
	bool m_isEroded;
	bool m_isBlur;
	bool m_isAnimation;

	

	wxSize _minSize;
	void Censore();
	void Erode();
	void Animate();
	void ProcessExif(const char* path);
	void DisplayExif(FIBITMAP* dib, FREE_IMAGE_MDMODEL model);
	cimg_library::CImg<unsigned char> wxImageToCImg(wxImage image);
	wxImage CImgTowxImage(cimg_library::CImg<unsigned char> image);
	void EnableControls();
	void Repaint();


public:
	wxImage Img_Org;
	wxImage Img_Copy;
	wxBitmap m_isAnimationFrames[60];



};

#endif // __GUIMyFrame1__
